In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Display the first 8 rows of the dataset.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [5]:
# Display the last 12 rows of the dataset.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# Show 10 random rows from the dataset.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5843,5844,15813327,Romani,710,France,Male,21,4,109130.96,2,1,1,56191.99,0
4679,4680,15756975,Montemayor,777,Spain,Female,35,3,0.00,2,1,1,17257.72,0
836,837,15585036,Okoli,694,Spain,Female,37,3,0.00,2,1,1,147012.22,0
8114,8115,15607269,Costa,492,Germany,Female,49,2,151249.45,2,1,1,167237.94,0
7674,7675,15660871,Ch'ang,665,France,Male,28,8,137300.23,1,1,0,90174.83,0
8235,8236,15760177,Lombardi,564,Spain,Male,37,9,100252.18,1,1,1,146033.52,0
9004,9005,15723153,Wearing,708,Spain,Male,33,3,0.00,2,1,0,138613.21,0
5168,5169,15579559,Chienezie,544,Spain,Male,30,8,145241.63,1,1,1,80676.83,0
8389,8390,15715345,Sergeyeva,743,Spain,Male,25,6,0.00,2,1,0,129740.11,0
929,930,15590876,Knupp,764,France,Female,24,7,106234.02,1,0,0,115676.38,0

In [7]:
# Find the shape of the dataset.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.shape

(10000, 14)

In [8]:
# Display complete information about the dataset using one method.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [10]:
# Print the names of all columns in the dataset.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [11]:
# Find the data type of every column.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [15]:
# Check for missing values in every column using.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
print(df.isnull().sum())
print("*"*30)
print(df.isna().sum())

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
******************************
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [20]:
# Select only one column:
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [19]:
# Select the following multiple columns:
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df[["CustomerId","Surname","Balance","Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [24]:
# Display only numeric columns using select_dtypes().
df.select_dtypes(include = ["object"]).columns

Index(['Surname', 'Geography', 'Gender'], dtype='object')

In [25]:
# Generate the statistical summary of all numeric columns using describe().
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [28]:
# Check for duplicate rows in the dataset,How many duplicate rows exist,Remove all duplicate rows.
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df.duplicated().sum()
# df.drop_duplicates(inplace = true) --- this will be used if any duplicate value is found

np.int64(0)

In [32]:
# Count the number of customers in each class of the Exited column using value_counts().
df = pd.read_csv(r"C:\Users\Abdul Sofiyan\Downloads\Bank_customer_churn.csv")
df ["CustomerId"].value_counts()

CustomerId
15634602    1
15667932    1
15766185    1
15667632    1
15599024    1
           ..
15599078    1
15702300    1
15660735    1
15671390    1
15628319    1
Name: count, Length: 10000, dtype: int64

# operators and loops

In [37]:
#Take two numbers from user. Perform all arithmetic operations and also check which number is greater using comparison operators.
a= int(input("enter a number"))
b= int(input("enter a number"))
print(a+b)
print(a-b)
print(a%b)
print(a*b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

enter a number 10
enter a number 20

30
-10
10
200
False
True
False
True

In [42]:
# Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop completely when number 40 is reached using break.
for i in range(1,51):
    if i == 40:
         break
    if i%5 == 0:
         continue
        
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

In [49]:
# Take numbers from user until they enter negative number. Calculate sum and average using while loop.
start = 0
while True:
    a= int(input("enter a number"))
    if a <= 0:
        break
    start = a+start
print(start)

enter a number 10
enter a number 23
enter a number 43
enter a number 4
enter a number 0

80